### PR TITLE
Wording changed for login page

### PR DESCRIPTION
**Pull request by JessicaVaughan2022**

### CODE REVIEW

**Review by DeviFitz — APPROVED** [review]
Looks great!

**Review by LongShotPlaya — APPROVED** [review]
Amazing, how did you get all that done so quick??? How do I become as cool as you??

**Review by Vyryty — APPROVED** [review]
I'd add an exclamation mark, but looks good!

**Review by WilsonTrin — APPROVED** [review]
👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Pull request merged**
