### PR TITLE
Updated service.js jn

### PR DESCRIPTION
**Pull request by LongShotPlaya**
This is not finished, but this push has the service.js file updated for asset-t3 from tutorials

### CODE REVIEW

**Review by WilsonTrin — APPROVED** [review]
No noticeable spelling errors

**Review by DeviFitz — APPROVED** [review]
Looks good

**Review by Vyryty — APPROVED** [review]
We definitely need some more stuff, but thanks for the bug fix!

**Review by JessicaVaughan2022 — APPROVED** [review]
looks good to me!

**Pull request merged**
