### PR TITLE
Create navbar tw

### PR DESCRIPTION
**Pull request by WilsonTrin**
Should fulfill the AC but it needs other pages to go into action

### CODE REVIEW

**Review by DeviFitz — APPROVED** [review]
Looks good

**Review by LongShotPlaya — APPROVED** [review]
Hits all AC's and looks great, nice job!!!

**Review by JessicaVaughan2022 — APPROVED** [review]
Looks good to me

**Review by Vyryty — APPROVED** [review]
Should be find until we need to start considering how permissions affect things on the frontend.

**Pull request merged**
