### PR TITLE
Service files jn

### PR DESCRIPTION
**Pull request by LongShotPlaya**
I've tested most of these, but there's a lot to test, the ones I did test worked like a charm. If you have made a page already, I recommend moving your code to the page I already made, just to avoid potential errors.

### CODE REVIEW

**Review by DeviFitz — APPROVED** [review]
Looks good!

**Review by Vyryty — APPROVED** [review]
Seems like all the necessary changes have been made. Good job!

**Review by WilsonTrin — APPROVED** [review]
good

**Review by JessicaVaughan2022 — APPROVED** [review]
looks good to me!

**Pull request merged**
